### ISSUE TITLE
[chalenge] Key press to select a multiple-choice answer is broken

### ISSUE THREAD

**Issue by vgx32** [trungtle/vietspeak#12]
Currently has no effect

**Comment by vgx32** [comment]
I think this is an open issue in meteor https://github.com/meteor/meteor/issues/2024

**Comment by trungtle** [comment]
@vgx32 Damn you meteor! Although, if you look closely, I think it only doesn't work with the Template.body.events(), but other custom templates should work

**Comment by trungtle** [comment]
@vgx32 Possible workaround? http://stackoverflow.com/questions/26438853/how-to-detect-events-on-entire-document-in-meteor-js

**Comment by hanam27** [comment]
Ok, got it. Will check it out tomorrow. 

```
 On Sunday, 5 July 2015, 18:02, Trung Le <notifications@github.com> wrote:
```

 @vgx32 Possible workaround? http://stackoverflow.com/questions/26438853/how-to-detect-events-on-entire-document-in-meteor-js—

**Comment by trungtle** [comment]
Hey @hanam27 , you don't have to worry about this

**Comment by vgx32** [comment]
@trungtle yea, I saw that post. The problem is his solution isn't fixing the issue... another fixe I've found requires a little bit of restructuring to the template code:  [use jquery events](http://stackoverflow.com/questions/13618262/keypress-events-stopped-working-outside-of-input-elements-in-meteor-after-upda) 

At the moment I don't see this as a high-priority issue because it doesn't reduce functionality. I'll work on other things for a bit

**Comment by trungtle** [comment]
Fixed in master
