### ISSUE TITLE
[challenge] should not be able to change the answer to a question after pressing submit button

### ISSUE THREAD

**Issue by vgx32** [trungtle/vietspeak#15]
repro:
1. open a multiple choice question
2. click an answer and click submit key once
3. click on an answer and click on submit key again

also happens in translate typing questions

**Comment by trungtle** [comment]
Ah, need to disable them all after submission

**Comment by vgx32** [comment]
I'll take a look when I get some time

**Comment by trungtle** [comment]
Fixed. No longer happens
